### ISSUE TITLE
集成友盟之后home键退出应用点击图标重新进入应用崩溃

### ISSUE THREAD

**Issue by lekenny** [esseak/rn-umeng#11]
`E/MobclickAgent: onPause called before onResume`

**Comment by esseak** [comment]
@Override
protected void onResume() {
    super.onResume();
    MobclickAgent.onResume(this);
}

@Override
protected void onPause() {
    super.onPause();
    MobclickAgent.onPause(this);
}

在你RootView的activity里添加上面代码

**Comment by lekenny** [comment]
好的  谢啦
