### ISSUE TITLE
寻求帮助, 不知道如何使用

### ISSUE THREAD

**Issue by alexlipe** [esseak/rn-umeng#15]
请问有使用的实际例子么? 如果是按照文档的说明,应该是每个文件都要写startWithAppkey ?   能不能和原生一样在代码里写一次appkey 就行?  该怎么写?

**Comment by esseak** [comment]
没有demo，这个库只是做了简单的封装，如果有问题可以提，欢迎pr。startWithAppkey 在打点方法前写一次就行了，多次也没关系 只是会重复调用而已。

**Comment by alexlipe** [comment]
感谢回复. 
打点位置比较多. 可以用官方的方法写入appkey么?   不然后期修改key比较麻烦.
比如ios 引用MobClick.h 按照官方的方法声明appkey .  android用meta 声明.

**Comment by esseak** [comment]
可以的，可以使用原生的方式

**Comment by alexlipe** [comment]
感谢.
