### ISSUE TITLE
E/MobclickAgent:  not legitimate!

### ISSUE THREAD

**Issue by pampang** [esseak/rn-umeng#19]
E/MobclickAgent:  not legitimate!

在onEvent的时候报错如上。
请问可能是什么原因导致的？

**Comment by pampang** [comment]
@esseak 求助求助！

**Comment by esseak** [comment]
能给多一些信息吗？

**Comment by pampang** [comment]
```
       UmengAnalytics.onEvent('test0', {
          hello: '123123',
        }, 123);

        UmengAnalytics.onEvent('test1', {
          hello: '123123',
        });

        UmengAnalytics.onEvent('test2');
```

接入后执行上述代码，都会报错`E/MobclickAgent: not legitimate!`
也仅仅只有这么多的信息了...

**Comment by esseak** [comment]
你填入有盟的appkey了吗？ 
你可以在android的manifest里按照官方文档基础appkey

**Comment by pampang** [comment]
已经填写啦。
在mainActivity中集成了onResume, onPause之后，终于可以正常发送数据了！！

有几个问题感到很奇怪：
1、为什么在MainApplication中的onActivityResumed，不会被触发？
2、作者你有在android原生里写onResume吗？

**Comment by esseak** [comment]
在你原生的activity里添加 下面代码试试
onResume and onPause

@Override
protected void onResume() {
    super.onResume();
    MobclickAgent.onResume(this);
}

@Override
protected void onPause() {
    super.onPause();
    MobclickAgent.onPause(this);
}

**Comment by pampang** [comment]
我加上啦，加上之后就正常运行了~感谢 @esseak 的回答~
