### ISSUE TITLE
ios上报错

### ISSUE THREAD

**Issue by sunny20131314** [esseak/rn-umeng#23]
在模拟器上运行报错

"react": "^15.4.1",
"react-native": "^0.39.2",
"rn-umeng": "^1.0.5"

xcode 8.2beta版本。

操作如下：
npm install rn-umeng --save
rnpm link rn-umeng

显示ios&&android link 成功

错误如下：
Undefined symbols for architecture x86_64:
  "_compress2", referenced from:
      +[UMANDeflated deflatedDataPrefixedWith:level:source:] in libRCTUmeng.a(UMDeflated.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![image](https://cloud.githubusercontent.com/assets/13795567/21838168/84b3f330-d80b-11e6-9275-e6ac422f6367.png)

google后搜到的结果:
1. 因为umeng统计不支持 bitcode的，设置为 no -> 无效
2. 删除RCTUmeng.xcodeproj的 reference 后，手动添加链接库 -> 无效。

不知道是哪里的错误，请大神指教，谢谢！

**Comment by esseak** [comment]
看起来像友盟本身的问题，手动添加库都无效可以自己升级工程自带的友盟库，在UMAnalytics_Sdk文件夹里。

**Comment by sunny20131314** [comment]
安装官网，下载了sdk， 导入之后好了，只是原生不会，所以是直接导入到自己的项目里 /(ㄒoㄒ)/~~

**Comment by esseak** [comment]
@sunny20131314 是版本问题吗？ 我稍后更新一下项目的包

**Comment by sunny20131314** [comment]
是友盟sdk的问题
