### ISSUE TITLE
was called with 3 arguments but expects 1 arguments

### ISSUE THREAD

**Issue by Aevit** [esseak/rn-umeng#28]
> RN 版本：0.44.0
> rn-umeng 版本：1.0.6

iOS 下类似这样使用会有问题：

```js
import MobclickAgent from 'rn-umeng';

MobclickAgent.onEvent("login_count");
```

报错如下：
![image](http://ww1.sinaimg.cn/large/6f68c4d7gy1ffgdwio334j20ku112tdg.jpg)  

试了在 iOS 工程里把 `onEvent` 方法名改为 `onEvent1` 或其它就没问题了：  

```objective-c
RCT_EXPORT_METHOD(onEvent1:(NSString *)eventId)
{
    [MobClick event:eventId];
}
```

不知道具体哪里导致的？

试过把工程里的方法名分别改为 `onEvent1` `onEvent2`，但是使用时报找不到方法：

```js
MobclickAgent.onEvent1("login_count");
```

![image](http://ww1.sinaimg.cn/large/6f68c4d7gy1ffge43pe22j213y0ci0xr.jpg)

**Comment by messense** [comment]
Same issue
