### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by anysome** [esseak/rn-umeng#3]
header search maybe wrong.
$(SRCROOT)/../../../node_modules/react-native/React
![12](https://cloud.githubusercontent.com/assets/233960/15063351/0b84bd5e-137c-11e6-9318-e9db1ceaef38.png)

and libz.tbd need to be added.

**Comment by esseak** [comment]
Thanks @anysome 
RN header files path maybe different in project, so modify the right path by yourself or run some scripts in rnpm link progress to set right path.

**Comment by cbcye** [comment]
![image](https://cloud.githubusercontent.com/assets/869074/17763981/fa208a64-654e-11e6-96bd-5765e923d398.png)
