### ISSUE TITLE
Upgrade SDK

### ISSUE THREAD

**Issue by messense** [esseak/rn-umeng#31]
收到了友盟的邮件：

> 亲爱的【友盟+】用户，
感谢您长期以来对【友盟+】的支持。我们深感荣幸，陪伴了您的成长，感谢您对我们的信任。
为了给您提供更优质的服务，强烈建议您对老版本SDK进行升级。
新版本采用新的加密协议和发送数据机制，将更有效的提升数据采集的稳定性、安全性和准确性。
考虑到老版本SDK不能提供更完备的安全保护，我们将于2017年8月31日起不再对上述版本的SDK进行技术支持与维护，届时【友盟+】应用统计和游戏统计后台不显示当日实时数据，而且有可能出现数据丢失等情况。
为保证稳定的数据服务，请您尽快升级。
老版本SDK包括：
1、【友盟+】应用统计SDK iOS 3.1.8及以下、Android SDK 5.2.4及以下
2、【友盟+】游戏统计SDK iOS 3.5.8.0及以下、Android 5.5.3.0以下
3、【友盟+】游戏统计SDK cocos2dx 4.1以下、Unity3D 1.6及以下

**Comment by cbjs** [comment]
iOS好像统计不准确了，是不是必须要升级sdk了

**Comment by esseak** [comment]
刚刚合了新的sdk，可以在试试

**Comment by cbjs** [comment]
赞

**Comment by cbjs** [comment]
@esseak 没有发布新的版本吗？
